twig:
    file_name_pattern: '*.twig'
    date:
        format: 'd/m/Y'
        interval_format: '%d jours'
        timezone: 'Europe/Paris'
    number_format:
        decimals: 0
        decimal_point: ','
        thousands_separator: ' '
    paths: ['%kernel.project_dir%/templates']
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig' 
        # ['bootstrap_5_layout.html.twig']
    
when@test:
    twig:
        strict_variables: true
